services:
  ping:
    image: tugboatqa/node:14
    default: true
    expose: 3000
    subpath: true
    depends:
      - pong
    commands:
      start:
        - node ${TUGBOAT_ROOT}/ping &
      build:
        - apt-get update
        - apt-get install jq
        - npm i ${TUGBOAT_ROOT}/ping
  pong:
    image: tugboatqa/node:14
    expose: 3000
    checkout: true
    subpath: true
    commands:
      start:
        - node ${TUGBOAT_ROOT}/pong &
      build:
        - npm i ${TUGBOAT_ROOT}/pong

