services:
  ping:
    image: tugboatqa/node:14
    default: true
    expose: 3000
    subpath: true
    depends:
      - pong
    commands:
      start:
        - node ${TUGBOAT_ROOT}/ping &
      build:
        - apt-get update
        - apt-get install jq
        - mkdir ${TUGBOAT_ROOT}/hello
        - export PATH="${TUGBOAT_ROOT}/hello:$PATH"
        - npm i ${TUGBOAT_ROOT}/ping
    urls:
      - /main-acabnnqwz4zu6f9ytmpzx8zqb3rp3n5y
  pong:
    image: tugboatqa/node:14
    expose: 3000
    checkout: true
    subpath: true
    commands:
      start:
        - node ${TUGBOAT_ROOT}/pong &
      build:
        - npm i ${TUGBOAT_ROOT}/pong
