services:
  pong:
    image: tugboatqa/node:14
    expose: 3000
    checkout: true
    commands:
      start:
        - node ${TUGBOAT_ROOT}/pong/bad.js
        - node ${TUGBOAT_ROOT}/pongs &
      build:
        - npm i ${TUGBOAT_ROOT}/pong
