services:
  ping:
    image: tugboatqa/node:14
    default: true
    expose: 3000
    commands:
      start:
        - node ${TUGBOAT_ROOT}/ping &
      build:
        - npm i ${TUGBOAT_ROOT}/ping
  pong:
    image: tugboatqa/node:14
    expose: 3000
    commands:
      start:
        - node ${TUGBOAT_ROOT}/pong &
      build:
        - npm i ${TUGBOAT_ROOT}/pong
