services:
  ping:
    image: tugboatqa/node:14
    default: true
    expose: 3000
    depends:
      - pong
    commands:
      start:
        - node ${TUGBOAT_ROOT}/ping &
      build:
        - apt-get update
        - apt-get install jq
        - curl -H "Authorization: Token $TUGBOAT_DEFAULT_SERVICE_TOKEN" https://api.tugboat.qa/v3/previews/$TUGBOAT_PREVIEW_ID/services | jq '.[] | select(.name == "pong") | .urls[0]'
        - npm i ${TUGBOAT_ROOT}/ping
  pong:
    image: tugboatqa/node:14
    expose: 3000
    checkout: true
    commands:
      start:
        - node ${TUGBOAT_ROOT}/pong &
      build:
        - npm i ${TUGBOAT_ROOT}/pong
